Repository e-Luminous/src, pull requests merged in 2019-12, with the labels that each got.

#20 PostJSONphy: Post JSON APIData for each Dynamic Table
  .idea/.idea.src/.idea/contentModel.xml
  .idea/.idea.src/.idea/workspace.xml
  src/Controllers/ClassroomsController.cs
  src/Views/Classrooms/_ExpPhysicsPartial.cshtml
  src/eLuminous.db
  src/wwwroot/api/modules/_PostPhysicsExperiments.js
  src/wwwroot/api/modules/_PostPhysicsExperiments.js.map
  src/wwwroot/api/modules/_PostPhysicsExperiments.ts
Labels: future-factory, 👌🏽Passed

#26 Lightweight modules
  src/Controllers/ClassroomsController.cs
  src/Controllers/HomeController.cs
  src/Views/Classrooms/__StudentFriends__.cshtml
  src/Views/Classrooms/__StudentList__.cshtml
  src/Views/Home/GetPublicKeys.cshtml
  src/Views/Shared/_Layout.cshtml
  src/eLuminous.db-shm
  src/eLuminous.db-wal
  src/wwwroot/api/scripts/GetListOfStudentsForTeacher.js
  src/wwwroot/app/src/stylesheets/__initTeacherClassroomLayout.css
  src/wwwroot/app/src/stylesheets/__initialize__.css
Labels: 💡 enhancement, 🧐 In Review

#27 Std notice board
  src/Controllers/ClassroomsController.cs
  src/Views/Classrooms/_ExpPhysicsPartialTeacher.cshtml
  src/Views/Classrooms/__StudentFriends__.cshtml
  src/Views/Classrooms/__StudentList__.cshtml
  src/Views/Classrooms/__StudentNotices__.cshtml
  src/eLuminous.db
  src/wwwroot/api/scripts/GetExperimentsOfPhysicsTeacher.js
Labels: 💡 enhancement, 🧐 In Review

#28 Design fixer
  src/Controllers/ClassroomsController.cs
  src/Views/Classrooms/_ExpPhysicsPartialStudent.cshtml
  src/Views/Classrooms/__StudentFriends__.cshtml
  src/Views/Classrooms/__StudentList__.cshtml
  src/Views/Classrooms/__StudentNotices__.cshtml
  src/Views/Home/GetPublicKeys.cshtml
  src/Views/Shared/_LayoutStudent.cshtml
  src/Views/Shared/_LayoutStudentClassroom.cshtml
  src/Views/Shared/_LayoutTeacher.cshtml
  src/Views/Shared/_LayoutTeacherClassroom.cshtml
  src/Views/Students/__init__.cshtml
  src/Views/Teachers/__init__.cshtml
  src/eLuminous.db
  src/eLuminous.db-shm
  src/eLuminous.db-wal
  src/wwwroot/api/modules/_AnalysisContext.js
  src/wwwroot/api/modules/_PostPhysicsExperiments.js
  src/wwwroot/api/modules/_PostPhysicsExperiments.js.map
  src/wwwroot/api/modules/_PostPhysicsExperiments.ts
  src/wwwroot/app/lib/images/private/ill1.png
  src/wwwroot/app/lib/images/private/tenor.gif
  src/wwwroot/app/lib/images/private/undraw_children_4rtb.svg
  src/wwwroot/app/lib/images/private/undraw_having_fun_iais.png
  src/wwwroot/app/lib/images/private/undraw_online_friends_x73e.svg
  src/wwwroot/app/src/scripts/__ClassroomJoin.js
  src/wwwroot/app/src/scripts/__classroomCreate.js
  src/wwwroot/app/src/scripts/__initStudentClassroomLayout__.js
  src/wwwroot/app/src/stylesheets/__initStudentClassroomLayout__.css
  src/wwwroot/lib/jquery/ui.js
Labels: 🧐 In Review
