Repository e-Luminous/src, pull requests merged in 2019-11, with the labels that each got.

#7 Teacher classroom : Created Classroom, Dynamic Cards, Route Links
  .idea/.idea.src/.idea/contentModel.xml
  .idea/.idea.src/.idea/workspace.xml
  src/Controllers/ClassroomsController.cs
  src/Controllers/TeachersController.cs
  src/Views/Classrooms/__teacher__.cshtml
  src/Views/Teachers/__classrooms___.cshtml
  src/eLuminous.db
  src/eLuminous.db-shm
  src/eLuminous.db-wal
  src/wwwroot/app/src/scripts/__classroomCreate.js
Labels: In Review, enhancement

#8 Course enrollment: Student Joining Classroom by Providen Access Code, Dynamic Card view . Student Classroom Route Links
  .idea/.idea.src/.idea/contentModel.xml
  .idea/.idea.src/.idea/workspace.xml
  src/Controllers/ClassroomsController.cs
  src/Controllers/StudentsController.cs
  src/Models/Student.cs
  src/Views/Shared/_LayoutStudent.cshtml
  src/Views/Students/__classrooms___.cshtml
  src/Views/Students/__init__.cshtml
  src/eLuminous.db
  src/eLuminous.db-shm
  src/eLuminous.db-wal
  src/wwwroot/app/src/scripts/__ClassroomJoin.js
  src/wwwroot/app/src/scripts/__initStudentLayout__.js
  src/wwwroot/app/src/stylesheets/__initStudentLayout__.css
Labels: In Review, good first issue

#9 Functioned Authorization Logic, Fixed Authorization Bug
  .github/workflows/dotnetcore.yml
  .gitignore
  .idea/.idea.src/.idea/contentModel.xml
  .idea/.idea.src/.idea/workspace.xml
  src/Controllers/StudentsController.cs
  src/Controllers/TeachersController.cs
  src/eLuminous.db
  src/wwwroot/app/src/scripts/__classroomCreate.js
Labels: In Review, question

#13 Fixed classroom: Change Dynamic Cards Design, Fixed Verification create or join classrooms
  .idea/.idea.src/.idea/contentModel.xml
  .idea/.idea.src/.idea/workspace.xml
  src/Controllers/StudentsController.cs
  src/Controllers/TeachersController.cs
  src/wwwroot/app/src/scripts/__ClassroomJoin.js
  src/wwwroot/app/src/scripts/__classroomCreate.js
Labels: In Review, Passed, documentation

#16 Exp phy: Initiated physics experiments from JSON
  src/Views/Classrooms/__StudentExperiments__.cshtml
  src/eLuminous.db
  src/wwwroot/api/scripts/GetExperimentsOfPhysics.js
Labels: 💡 enhancement, 🧐 In Review

#17 Optimizer a : Optimized Scripts and Razor
  .idea/.gitignore
  .idea/.idea.src/.idea/contentModel.xml
  .idea/.idea.src/.idea/workspace.xml
  .idea/httpRequests/2019-11-02T112610.200.json
  .idea/httpRequests/2019-11-02T113654.200.json
  .idea/httpRequests/http-requests-log.http
  src/Controllers/ClassroomsController.cs
  src/Views/Classrooms/_ErrorClassroomPartial.cshtml
  src/Views/Classrooms/_ExpChemistryPartial.cshtml
  src/Views/Classrooms/_ExpPhysicsPartial.cshtml
  src/Views/Classrooms/__StudentExperiments__.cshtml
  src/eLuminous.db
  src/eLuminous.db-shm
  src/eLuminous.db-wal
  src/wwwroot/api/scripts/GetExperimentsOfChemistry.js
  src/wwwroot/api/scripts/GetExperimentsOfPhysics.js
  src/wwwroot/app/src/scripts/__ClassroomJoin.js
  src/wwwroot/app/src/scripts/__classroomCreate.js
  src/wwwroot/app/src/scripts/__initStudentLayout__.js
  src/wwwroot/app/src/scripts/__initTeacherLayout__.js
  src/wwwroot/app/src/stylesheets/__initStudentClassroomLayout__.css
Labels: 💡 enhancement, 🧐 In Review

#18 Post exp: update Table tBody Dynamically
  .idea/.idea.src/.idea/contentModel.xml
  .idea/.idea.src/.idea/workspace.xml
  src/Views/Classrooms/_ExpPhysicsPartial.cshtml
  src/eLuminous.db
  src/eLuminous.db-shm
  src/eLuminous.db-wal
  src/wwwroot/api/scripts/GetExperimentsOfPhysics.js
Labels: future-factory, 👌🏽Passed, 💡 enhancement

#19 Bug fixer1
  .github/workflows/dotnetcore.yml
  .gitignore
  .idea/.idea.src/.idea/contentModel.xml
  .idea/.idea.src/.idea/workspace.xml
  .idea/.idea.src/riderModule.iml
  src/.gitignore
  src/Startup.cs
  src/Views/Classrooms/_ExpPhysicsPartial.cshtml
  src/Views/Shared/_LayoutStudentClassroom.cshtml
  src/eLuminous.db
  src/eLuminous.db-shm
  src/eLuminous.db-wal
  src/package-lock.json
  src/package.json
  src/src.csproj
  src/wwwroot/api/modules/_PostPhysicsExperiments.js
  src/wwwroot/api/modules/_PostPhysicsExperiments.js.map
  src/wwwroot/api/modules/_PostPhysicsExperiments.ts
  src/wwwroot/api/modules/tsconfig.json
  src/wwwroot/api/scripts/GetExperimentsOfPhysics.js
  src/wwwroot/app/src/stylesheets/__initStudentClassroomLayout__.css
Labels: 💡 enhancement, 🧐 In Review
